package it.fadeout.risckit.business;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPageEventHelper;
import com.itextpdf.text.pdf.PdfWriter;




public class PdfHeaderFooter extends PdfPageEventHelper {
	
	private final String FOOTER = "This fact sheet is automatically-generated by the WEB-GIS impact-oriented database, developed as part of the RISC-KIT project (grant agreement 603458). RISC-KIT is supported by the European "
			+ "Commission under the Environment (including climate change) Theme of the 7th Framework Programme for Research and Technological Development. The information contained in this fact sheet reflects the views of the "
			+ "author(s) and the European Union cannot be held responsible for any use which may be made of the information contained therein. For more information, please contact RISC-Kit project coordinator Ap Van Dongeren "
			+ "(ap.vandongeren@deltares.nl) of work package leader Paolo Ciavola (cvp@unife.it).";
	
	
	 /**
     * Adds the header and the footer.
     * @see com.itextpdf.text.pdf.PdfPageEventHelper#onEndPage(
     *      com.itextpdf.text.pdf.PdfWriter, com.itextpdf.text.Document)
     */
    public void onEndPage(PdfWriter writer, Document document) {
        
    	try {
    		document.add(Descrizione(FOOTER));
		} catch (DocumentException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	
    }
    
    private Paragraph Descrizione(String sValue)
	{
		Font oFont = new Font();
		oFont.setStyle(oFont.ITALIC);
		Paragraph oDescrizione = new Paragraph(sValue, oFont);
		oDescrizione.setAlignment(oDescrizione.ALIGN_JUSTIFIED);
		oDescrizione.setSpacingBefore(150);
		return oDescrizione;
	}
    
    

}
